### ISSUE TITLE
row-level security

### ISSUE THREAD

**Issue by dpdonohue** [dergachev/solr-security-proxy#7]
Solr can be used as a persistent document store.
I would like to implement rules that state things like:
* a record may only be updated by administrators or by the record owner
* a record may only be viewed by members of a particular group or role

So I would think I might need to inject some logic in the proxy, to do things like
* for updates, first check (search) to see if the current user is the owner of the record to be updated, or 
* for searches, first append some group/role info onto the query.

So my questions are-
Does solr-security-proxy support introducing our own logic?  
Or does it in any other way support row-level security?

If necessary, can you think of a means how this capability can be added?  If so I am prepared to do some dev.

**Comment by frank-dspeed** [comment]
Maybe a more robust idea is to simply put a proxy in front of the proxy if is admin then proxy to solr proxy else proxy to solr directly you can archive this via node proxy module google node proxy it supports auth.

i think this can be closed!!!!
